# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
# uncomment if want full left master
#  - board: nice_nano_v2
#    shield: rollow_left
  - board: nice_nano_v2
    shield: rollow_right
  - board: seeeduino_xiao_ble
    shield: settings_reset  

    # Add custom dongle and a peripheral left corne
  - board: seeeduino_xiao_ble
    shield: dongle
  - board: nice_nano_v2
    shield: rollow_peripheral_left #peripheral_left is the one you flash left side with when also using dongle
